// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokebook.core.Data;

namespace Pokebook.core.Migrations
{
    [DbContext(typeof(PokebookContext))]
    [Migration("20190720101008_AddNewDbSets")]
    partial class AddNewDbSets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokebook.core.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Image");

                    b.Property<string>("LastMessage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NumberOfMessages");

                    b.Property<int>("NumberOfUsers");

                    b.Property<string>("Theme");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreateDate = new DateTime(2019, 7, 20, 12, 10, 7, 355, DateTimeKind.Local).AddTicks(1268),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 434, DateTimeKind.Local).AddTicks(6223),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Awesome Chat",
                            NumberOfMessages = 0,
                            NumberOfUsers = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreateDate = new DateTime(2019, 7, 20, 10, 10, 7, 356, DateTimeKind.Local).AddTicks(6139),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 434, DateTimeKind.Local).AddTicks(6385),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Another awesome Chat",
                            NumberOfMessages = 0,
                            NumberOfUsers = 0
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Accepted");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("IdApprover");

                    b.Property<Guid>("IdRequester");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Accepted = true,
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(820),
                            IdApprover = new Guid("00000000-0000-0000-0000-000000000002"),
                            IdRequester = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Accepted = false,
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(890),
                            IdApprover = new Guid("63ed99a2-e0dc-46d5-4c0c-08d6bce3eda7"),
                            IdRequester = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ChatId");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageName");

                    b.Property<DateTime>("SendDate");

                    b.Property<Guid>("SenderId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(1963),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Hello Jon. This is Tyrion"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(2034),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "Hello Tyrion. I'm Jon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(2091),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "This is a chat with myself. Is this even possible?"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Move", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Generation");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PokemonCatchId");

                    b.Property<Guid?>("PokemonId");

                    b.HasKey("Id");

                    b.HasIndex("PokemonCatchId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("Pokebook.core.Models.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("HasAllolanForm");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Location");

                    b.Property<int>("MaxCP");

                    b.Property<int>("MaxHP");

                    b.Property<float>("MaxHeight");

                    b.Property<float>("MaxWeight");

                    b.Property<int>("MinCP");

                    b.Property<int>("MinHP");

                    b.Property<float>("MinHeight");

                    b.Property<float>("MinWeight");

                    b.Property<short>("NDex");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PokemonId");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(4339),
                            Description = "It bears the seed of a plant on its back from birth. The seed slowly develops. Researchers are unsure whether to classify Bulbasaur as a plant or animal. Bulbasaur are extremely calm and very difficult to capture in the wild. ",
                            HasAllolanForm = false,
                            ImgUrl = "Bulbasaur.png",
                            Location = "Starter",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)1,
                            Name = "Bulbasaur"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(4521),
                            Description = "When the bulb on its back grows large, it appears to lose the ability to stand on its hind leg",
                            HasAllolanForm = false,
                            ImgUrl = "Ivysaur.png",
                            Location = "Evolve Bulbasaur",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)2,
                            Name = "Ivysaur"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(4624),
                            Description = "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
                            HasAllolanForm = false,
                            ImgUrl = "Venusaur.png",
                            Location = "Evolve Ivysaur",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)3,
                            Name = "Venusaur"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(4721),
                            Description = "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
                            HasAllolanForm = false,
                            ImgUrl = "Charmander.png",
                            Location = "Starter",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)4,
                            Name = "Charmander"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(4823),
                            Description = "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
                            HasAllolanForm = false,
                            ImgUrl = "Charmeleon.png",
                            Location = "Evolve Charmander",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)5,
                            Name = "Charmeleon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(4918),
                            Description = "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
                            HasAllolanForm = false,
                            ImgUrl = "Charizard.png",
                            Location = "Evolve Charmeleon",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)6,
                            Name = "Charizard"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5017),
                            Description = "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
                            HasAllolanForm = false,
                            ImgUrl = "Squirtle.png",
                            Location = "Starter",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)7,
                            Name = "Squirtle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5110),
                            Description = "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance",
                            HasAllolanForm = false,
                            ImgUrl = "Wartortle.png",
                            Location = "Evolve Squirtle",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)8,
                            Name = "Wartortle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5204),
                            Description = "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.",
                            HasAllolanForm = false,
                            ImgUrl = "Blastoise.png",
                            Location = "evolve Wartortle",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)9,
                            Name = "Blastoise"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5303),
                            Description = "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
                            HasAllolanForm = false,
                            ImgUrl = "Caterpie.png",
                            Location = "Routes 2, 24 and 25,Viridian Forest",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)10,
                            Name = "Caterpie"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5396),
                            Description = "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body",
                            HasAllolanForm = false,
                            ImgUrl = "Metapod.png",
                            Location = "Routes 24 and 25, Viridian Forest or evolve Caterpie",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)11,
                            Name = "Metapod"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5493),
                            Description = "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
                            HasAllolanForm = false,
                            ImgUrl = "Butterfree.png",
                            Location = "Evolve Metapod",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)12,
                            Name = "Butterfree"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5586),
                            Description = "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
                            HasAllolanForm = false,
                            ImgUrl = "Weedle.png",
                            Location = "Routes 2, 24, and 25, Viridian Forest",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)13,
                            Name = "Weedle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5678),
                            Description = "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.",
                            HasAllolanForm = false,
                            ImgUrl = "Kakuna.png",
                            Location = "Routes 24 and 25, Viridian Forest",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)14,
                            Name = "Kakuna"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5776),
                            Description = "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
                            HasAllolanForm = false,
                            ImgUrl = "Beedrill.png",
                            Location = "Evolve Kakuna",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)15,
                            Name = "Beedrill"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5868),
                            Description = "Is a small, quadruped rodent Pokémon. Its most notable feature is its large teeth.",
                            HasAllolanForm = true,
                            ImgUrl = "Rattata.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)19,
                            Name = "Rattata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(5966),
                            Description = "Is a humanoid Pokémon with an ovoid body. Hitmonlee's legs freely contract and stretch similar to a coiled spring.",
                            HasAllolanForm = false,
                            ImgUrl = "Hitmonlee.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)106,
                            Name = "Hitmonlee"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(6060),
                            Description = "Has an extremely sharp sense of direction and homing instincts.",
                            HasAllolanForm = false,
                            ImgUrl = "Pidgey.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)16,
                            Name = "Pidgey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(6152),
                            Description = "Creates gases within its body by mixing toxins with garbage, and produces more gas in higher temperatures.",
                            HasAllolanForm = false,
                            ImgUrl = "Koffing.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)109,
                            Name = "Koffing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(6379),
                            Description = "Is a tiny, brown Pokémon that seems to be perpetually buried within the earth, leaving only its head visible.",
                            HasAllolanForm = true,
                            ImgUrl = "Diglett.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)50,
                            Name = "Diglett"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000095"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(6482),
                            Description = "Resembles a giant chain of gray boulders that become smaller towards the tail.",
                            HasAllolanForm = false,
                            ImgUrl = "Onix.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)95,
                            Name = "Onix"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000092"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(6992),
                            Description = "Has no true form, due to 95% of its body being poisonous gas.",
                            HasAllolanForm = false,
                            ImgUrl = "Gastly.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)92,
                            Name = "Gastly"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(7297),
                            Description = "Is covered in yellow fur with two horizontal brown stripes on its back.",
                            HasAllolanForm = true,
                            ImgUrl = "Pikachu.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)25,
                            Name = "Pikachu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000150"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(7405),
                            Description = "Is a Pokémon created by science. It is a bipedal, humanoid creature with some feline features.",
                            HasAllolanForm = false,
                            ImgUrl = "Mewtwo.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)150,
                            Name = "Mewtwo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000087"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(7669),
                            Description = "Has a snowy white, furry body, which renders it virtually invisible in snowy conditions.",
                            HasAllolanForm = false,
                            ImgUrl = "Dewgong.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)87,
                            Name = "Dewgong"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000147"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 437, DateTimeKind.Local).AddTicks(7770),
                            Description = "is filled with life energy. Dratini is constantly growing, and can thus reach lengths of over six feet.",
                            HasAllolanForm = false,
                            ImgUrl = "Dratini.png",
                            Location = "Somewhere",
                            MaxCP = 0,
                            MaxHP = 0,
                            MaxHeight = 0f,
                            MaxWeight = 0f,
                            MinCP = 0,
                            MinHP = 0,
                            MinHeight = 0f,
                            MinWeight = 0f,
                            NDex = (short)147,
                            Name = "Dratini"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonCatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CP");

                    b.Property<DateTime?>("Created");

                    b.Property<int>("HP");

                    b.Property<float>("Height");

                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("UserId");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("UserId");

                    b.ToTable("PokemonCatches");
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonType", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("TypeId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9340),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9410),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9469),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9518),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000003"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9565),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000003"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9611),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000004"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9656),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000005"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9702),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9750),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9796),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000007"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9840),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000008"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9883),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000009"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9927),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000010"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 438, DateTimeKind.Local).AddTicks(9970),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000011"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(14),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000012"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(62),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000012"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(107),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000013"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(152),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000013"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(196),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000014"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(241),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000014"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(285),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(329),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(379),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000019"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(424),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000106"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(469),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000016"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(513),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000016"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(557),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000109"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(601),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000050"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(646),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000095"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(753),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000095"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(799),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000092"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(846),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000092"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(892),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000025"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(937),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000150"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(982),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000087"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(1027),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000087"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(1076),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000147"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(1122),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonUser", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("UserId");

                    b.Property<short>("Catches");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PokemonUsers");
                });

            modelBuilder.Entity("Pokebook.core.Models.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid?>("MoveId");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TypeId");

                    b.Property<Guid?>("TypeId1");

                    b.HasKey("Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("TypeId");

                    b.HasIndex("TypeId1");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Colour = "#A8A878",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4292),
                            Name = "Normal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Colour = "#C03028",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4356),
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Colour = "#A890F0",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4408),
                            Name = "Flying"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Colour = "#A040A0",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4457),
                            Name = "Poison"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Colour = "#E0C068",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4511),
                            Name = "Ground"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Colour = "#B8A038",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4559),
                            Name = "Rock"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Colour = "#A8B820",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4609),
                            Name = "Bug"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Colour = "#705898",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4657),
                            Name = "Ghost"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Colour = "#B8B8D0",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4705),
                            Name = "Steel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Colour = "#F08030",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4754),
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Colour = "#6890F0",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4801),
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Colour = "#78C850",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4852),
                            Name = "Grass"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Colour = "#F8D030",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4900),
                            Name = "Electric"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Colour = "#F85888",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4946),
                            Name = "Psychic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Colour = "#98D8D8",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(4993),
                            Name = "Ice"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Colour = "#7038F8",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(5040),
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Colour = "#705848",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(5088),
                            Name = "Dark"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Colour = "#EE99AC",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(5134),
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("CoverPicture");

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FavoritePokemon");

                    b.Property<string>("FavoritePokemonGame");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTime>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<int>("NumberOfFriends");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            CoverPicture = "Mt._Molteau.png",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(8532),
                            EmailConfirmed = false,
                            FavoritePokemon = "Pikachu",
                            FavoritePokemonGame = "Pokemon Red",
                            FirstName = "Tyrion",
                            LastName = "Lannister",
                            LockoutEnabled = false,
                            LockoutEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfFriends = 0,
                            PasswordHash = "PW7h5Yl70M3o3LA9YQ5wUG+ycD7H01aXrDizkpC4lBX7hP/k",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "Pikachu.png",
                            TwoFactorEnabled = false,
                            UserName = "TyrionLannister"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AccessFailedCount = 0,
                            CoverPicture = "mountain.jpg",
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(8688),
                            EmailConfirmed = false,
                            FirstName = "Jon",
                            LastName = "Snow",
                            LockoutEnabled = false,
                            LockoutEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfFriends = 0,
                            PasswordHash = "PW7h5Yl70M3o3LA9YQ5wUG+ycD7H01aXrDizkpC4lBX7hP/k",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "Magikarp.png",
                            TwoFactorEnabled = false,
                            UserName = "JonSnow"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.UserChat", b =>
                {
                    b.Property<Guid>("ChatId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChats");

                    b.HasData(
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(9690),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(9749),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 12, 10, 8, 439, DateTimeKind.Local).AddTicks(9800),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Friendship", b =>
                {
                    b.HasOne("Pokebook.core.Models.User")
                        .WithMany("Friendships")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Pokebook.core.Models.Message", b =>
                {
                    b.HasOne("Pokebook.core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.Move", b =>
                {
                    b.HasOne("Pokebook.core.Models.PokemonCatch")
                        .WithMany("Moves")
                        .HasForeignKey("PokemonCatchId");

                    b.HasOne("Pokebook.core.Models.Pokemon")
                        .WithMany("Moves")
                        .HasForeignKey("PokemonId");
                });

            modelBuilder.Entity("Pokebook.core.Models.Pokemon", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon")
                        .WithMany("Evolutions")
                        .HasForeignKey("PokemonId");
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonCatch", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonType", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.Type", "Type")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonUser", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.Type", b =>
                {
                    b.HasOne("Pokebook.core.Models.Move")
                        .WithMany("Types")
                        .HasForeignKey("MoveId");

                    b.HasOne("Pokebook.core.Models.Type")
                        .WithMany("Advantages")
                        .HasForeignKey("TypeId");

                    b.HasOne("Pokebook.core.Models.Type")
                        .WithMany("Disadvantages")
                        .HasForeignKey("TypeId1");
                });

            modelBuilder.Entity("Pokebook.core.Models.UserChat", b =>
                {
                    b.HasOne("Pokebook.core.Models.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
