// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokebook.core.Data;

namespace Pokebook.core.Migrations
{
    [DbContext(typeof(PokebookContext))]
    [Migration("20190720095112_NewPokemonTables")]
    partial class NewPokemonTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokebook.core.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Image");

                    b.Property<string>("LastMessage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NumberOfMessages");

                    b.Property<int>("NumberOfUsers");

                    b.Property<string>("Theme");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreateDate = new DateTime(2019, 7, 20, 11, 51, 11, 236, DateTimeKind.Local).AddTicks(7783),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 179, DateTimeKind.Local).AddTicks(7395),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Awesome Chat",
                            NumberOfMessages = 0,
                            NumberOfUsers = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreateDate = new DateTime(2019, 7, 20, 9, 51, 11, 238, DateTimeKind.Local).AddTicks(2914),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 179, DateTimeKind.Local).AddTicks(7523),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Another awesome Chat",
                            NumberOfMessages = 0,
                            NumberOfUsers = 0
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Accepted");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("IdApprover");

                    b.Property<Guid>("IdRequester");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Accepted = true,
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 182, DateTimeKind.Local).AddTicks(1791),
                            IdApprover = new Guid("00000000-0000-0000-0000-000000000002"),
                            IdRequester = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Accepted = false,
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 182, DateTimeKind.Local).AddTicks(1862),
                            IdApprover = new Guid("63ed99a2-e0dc-46d5-4c0c-08d6bce3eda7"),
                            IdRequester = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ChatId");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageName");

                    b.Property<DateTime>("SendDate");

                    b.Property<Guid>("SenderId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 182, DateTimeKind.Local).AddTicks(3590),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Hello Jon. This is Tyrion"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 182, DateTimeKind.Local).AddTicks(3665),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "Hello Tyrion. I'm Jon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 182, DateTimeKind.Local).AddTicks(3726),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "This is a chat with myself. Is this even possible?"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Move", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Generation");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PokemonId");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("Pokebook.core.Models.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("HasAllolanForm");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Location");

                    b.Property<int>("MaxCP");

                    b.Property<int>("MaxHP");

                    b.Property<float>("MaxHeight");

                    b.Property<float>("MaxWeight");

                    b.Property<int>("MinCP");

                    b.Property<int>("MinHP");

                    b.Property<float>("MinHeight");

                    b.Property<float>("MinWeight");

                    b.Property<short>("NDex");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PokemonId");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonType", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("TypeId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("PokemonTypes");
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonUser", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("UserId");

                    b.Property<short>("Catches");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PokemonUsers");
                });

            modelBuilder.Entity("Pokebook.core.Models.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid?>("MoveId");

                    b.Property<string>("Name");

                    b.Property<Guid?>("TypeId");

                    b.Property<Guid?>("TypeId1");

                    b.HasKey("Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("TypeId");

                    b.HasIndex("TypeId1");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Pokebook.core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("CoverPicture");

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FavoritePokemon");

                    b.Property<string>("FavoritePokemonGame");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTime>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<int>("NumberOfFriends");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            CoverPicture = "Mt._Molteau.png",
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 182, DateTimeKind.Local).AddTicks(9447),
                            EmailConfirmed = false,
                            FavoritePokemon = "Pikachu",
                            FavoritePokemonGame = "Pokemon Red",
                            FirstName = "Tyrion",
                            LastName = "Lannister",
                            LockoutEnabled = false,
                            LockoutEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfFriends = 0,
                            PasswordHash = "PW7h5Yl70M3o3LA9YQ5wUG+ycD7H01aXrDizkpC4lBX7hP/k",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "Pikachu.png",
                            TwoFactorEnabled = false,
                            UserName = "TyrionLannister"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AccessFailedCount = 0,
                            CoverPicture = "mountain.jpg",
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 182, DateTimeKind.Local).AddTicks(9599),
                            EmailConfirmed = false,
                            FirstName = "Jon",
                            LastName = "Snow",
                            LockoutEnabled = false,
                            LockoutEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfFriends = 0,
                            PasswordHash = "PW7h5Yl70M3o3LA9YQ5wUG+ycD7H01aXrDizkpC4lBX7hP/k",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "Magikarp.png",
                            TwoFactorEnabled = false,
                            UserName = "JonSnow"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.UserChat", b =>
                {
                    b.Property<Guid>("ChatId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChats");

                    b.HasData(
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 183, DateTimeKind.Local).AddTicks(873),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 183, DateTimeKind.Local).AddTicks(930),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 7, 20, 11, 51, 12, 183, DateTimeKind.Local).AddTicks(977),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Friendship", b =>
                {
                    b.HasOne("Pokebook.core.Models.User")
                        .WithMany("Friendships")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Pokebook.core.Models.Message", b =>
                {
                    b.HasOne("Pokebook.core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.Move", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon")
                        .WithMany("Moves")
                        .HasForeignKey("PokemonId");
                });

            modelBuilder.Entity("Pokebook.core.Models.Pokemon", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon")
                        .WithMany("Evolutions")
                        .HasForeignKey("PokemonId");
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonType", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.Type", "Type")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonUser", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonUsers")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.Type", b =>
                {
                    b.HasOne("Pokebook.core.Models.Move")
                        .WithMany("Types")
                        .HasForeignKey("MoveId");

                    b.HasOne("Pokebook.core.Models.Type")
                        .WithMany("Advantages")
                        .HasForeignKey("TypeId");

                    b.HasOne("Pokebook.core.Models.Type")
                        .WithMany("Disadvantages")
                        .HasForeignKey("TypeId1");
                });

            modelBuilder.Entity("Pokebook.core.Models.UserChat", b =>
                {
                    b.HasOne("Pokebook.core.Models.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
