// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokebook.core.Data;

namespace Pokebook.core.Migrations
{
    [DbContext(typeof(PokebookContext))]
    [Migration("20191102131345_AddedPokemonProperties2")]
    partial class AddedPokemonProperties2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokebook.core.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Image");

                    b.Property<string>("LastMessage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NumberOfMessages");

                    b.Property<int>("NumberOfUsers");

                    b.Property<string>("Theme");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreateDate = new DateTime(2019, 11, 2, 14, 13, 44, 248, DateTimeKind.Local).AddTicks(2532),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 423, DateTimeKind.Local).AddTicks(4215),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Awesome Chat",
                            NumberOfMessages = 0,
                            NumberOfUsers = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreateDate = new DateTime(2019, 11, 2, 12, 13, 44, 249, DateTimeKind.Local).AddTicks(8381),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 423, DateTimeKind.Local).AddTicks(4342),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Another awesome Chat",
                            NumberOfMessages = 0,
                            NumberOfUsers = 0
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Accepted");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("IdApprover");

                    b.Property<Guid>("IdRequester");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Accepted = true,
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 425, DateTimeKind.Local).AddTicks(7605),
                            IdApprover = new Guid("00000000-0000-0000-0000-000000000002"),
                            IdRequester = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Accepted = false,
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 425, DateTimeKind.Local).AddTicks(7677),
                            IdApprover = new Guid("63ed99a2-e0dc-46d5-4c0c-08d6bce3eda7"),
                            IdRequester = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ChatId");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageName");

                    b.Property<DateTime>("SendDate");

                    b.Property<Guid>("SenderId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(2245),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Hello Jon. This is Tyrion"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(2339),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "Hello Tyrion. I'm Jon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ChatId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(2403),
                            SendDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "This is a chat with myself. Is this even possible?"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Move", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Generation");

                    b.Property<string>("Name");

                    b.Property<Guid>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Moves");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3548),
                            Description = "Deals damage with no additional effect.",
                            Generation = "1",
                            Name = "Hydro Pump",
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3619),
                            Description = "Deals damage and has an increased critical hit ratio.",
                            Generation = "1",
                            Name = "Razor Leaf",
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3678),
                            Description = "Deals damage and has a 10% chance of burning the target.",
                            Generation = "1",
                            Name = "Flamethrower",
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3733),
                            Description = "Deals damage and has a 10% chance of paralyzing the target.",
                            Generation = "1",
                            Name = "Thunderbold",
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3796),
                            Description = "Deals damage with no additional effect in battle.",
                            Generation = "1",
                            Name = "Cut",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3853),
                            Description = "The user of Fly will fly up high on the first turn, disappearing from view and becoming invulnerable to most attacks. On the second turn, Fly deals damage.",
                            Generation = "1",
                            Name = "Fly",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3909),
                            Description = "The user of Solar Beam will absorb light on the first turn. On the second turn, Solar Beam deals damage.",
                            Generation = "1",
                            Name = "Solar Beam",
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(3965),
                            Description = "Lowers the target's Speed by two stages.",
                            Generation = "1",
                            Name = "String Shot",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(4020),
                            Description = "Deals damage and has a 10% chance of confusing the target.",
                            Generation = "1",
                            Name = "Psybeam",
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(4081),
                            Description = "Deals damage and has a 10% chance of freezing the target.",
                            Generation = "1",
                            Name = "Ice Beam",
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000f")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("HasAlolanForm");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("ImgUrlAllolan");

                    b.Property<string>("ImgUrlShiny");

                    b.Property<string>("ImgUrlShiny_Alolan");

                    b.Property<string>("Location");

                    b.Property<int>("MaxCP");

                    b.Property<int>("MaxHP");

                    b.Property<float>("MaxHeight");

                    b.Property<float>("MaxWeight");

                    b.Property<int>("MinCP");

                    b.Property<int>("MinHP");

                    b.Property<float>("MinHeight");

                    b.Property<float>("MinWeight");

                    b.Property<short>("NDex");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(6406),
                            Description = "It bears the seed of a plant on its back from birth. The seed slowly develops. Researchers are unsure whether to classify Bulbasaur as a plant or animal. Bulbasaur are extremely calm and very difficult to capture in the wild. ",
                            HasAlolanForm = false,
                            ImgUrl = "Bulbasaur.png",
                            Location = "Starter",
                            MaxCP = 850,
                            MaxHP = 60,
                            MaxHeight = 0.7f,
                            MaxWeight = 6.9f,
                            MinCP = 10,
                            MinHP = 30,
                            MinHeight = 0.2f,
                            MinWeight = 2f,
                            NDex = (short)1,
                            Name = "Bulbasaur"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(6545),
                            Description = "When the bulb on its back grows large, it appears to lose the ability to stand on its hind leg",
                            HasAlolanForm = false,
                            ImgUrl = "Ivysaur.png",
                            Location = "Evolve Bulbasaur",
                            MaxCP = 1200,
                            MaxHP = 80,
                            MaxHeight = 1.5f,
                            MaxWeight = 9.9f,
                            MinCP = 300,
                            MinHP = 50,
                            MinHeight = 0.5f,
                            MinWeight = 5f,
                            NDex = (short)2,
                            Name = "Ivysaur"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(6666),
                            Description = "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
                            HasAlolanForm = false,
                            ImgUrl = "Venusaur.png",
                            Location = "Evolve Ivysaur",
                            MaxCP = 2500,
                            MaxHP = 120,
                            MaxHeight = 14f,
                            MaxWeight = 70f,
                            MinCP = 800,
                            MinHP = 70,
                            MinHeight = 7.2f,
                            MinWeight = 25f,
                            NDex = (short)3,
                            Name = "Venusaur"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(6999),
                            Description = "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
                            HasAlolanForm = false,
                            ImgUrl = "Charmander.png",
                            Location = "Starter",
                            MaxCP = 850,
                            MaxHP = 60,
                            MaxHeight = 0.7f,
                            MaxWeight = 6.9f,
                            MinCP = 10,
                            MinHP = 30,
                            MinHeight = 0.2f,
                            MinWeight = 2f,
                            NDex = (short)4,
                            Name = "Charmander"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(7123),
                            Description = "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
                            HasAlolanForm = false,
                            ImgUrl = "Charmeleon.png",
                            Location = "Evolve Charmander",
                            MaxCP = 1200,
                            MaxHP = 80,
                            MaxHeight = 1.5f,
                            MaxWeight = 9.9f,
                            MinCP = 300,
                            MinHP = 50,
                            MinHeight = 0.5f,
                            MinWeight = 5f,
                            NDex = (short)5,
                            Name = "Charmeleon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(7375),
                            Description = "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
                            HasAlolanForm = false,
                            ImgUrl = "Charizard.png",
                            Location = "Evolve Charmeleon",
                            MaxCP = 2500,
                            MaxHP = 120,
                            MaxHeight = 14f,
                            MaxWeight = 70f,
                            MinCP = 800,
                            MinHP = 70,
                            MinHeight = 7.2f,
                            MinWeight = 25f,
                            NDex = (short)6,
                            Name = "Charizard"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(7484),
                            Description = "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
                            HasAlolanForm = false,
                            ImgUrl = "Squirtle.png",
                            Location = "Starter",
                            MaxCP = 850,
                            MaxHP = 60,
                            MaxHeight = 0.7f,
                            MaxWeight = 6.9f,
                            MinCP = 10,
                            MinHP = 30,
                            MinHeight = 0.2f,
                            MinWeight = 2f,
                            NDex = (short)7,
                            Name = "Squirtle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(7599),
                            Description = "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance",
                            HasAlolanForm = false,
                            ImgUrl = "Wartortle.png",
                            Location = "Evolve Squirtle",
                            MaxCP = 1200,
                            MaxHP = 80,
                            MaxHeight = 1.5f,
                            MaxWeight = 9.9f,
                            MinCP = 300,
                            MinHP = 50,
                            MinHeight = 0.5f,
                            MinWeight = 5f,
                            NDex = (short)8,
                            Name = "Wartortle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(7709),
                            Description = "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.",
                            HasAlolanForm = false,
                            ImgUrl = "Blastoise.png",
                            Location = "evolve Wartortle",
                            MaxCP = 2500,
                            MaxHP = 120,
                            MaxHeight = 14f,
                            MaxWeight = 70f,
                            MinCP = 800,
                            MinHP = 70,
                            MinHeight = 7.2f,
                            MinWeight = 25f,
                            NDex = (short)9,
                            Name = "Blastoise"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(7822),
                            Description = "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
                            HasAlolanForm = false,
                            ImgUrl = "Caterpie.png",
                            Location = "Routes 2, 24 and 25,Viridian Forest",
                            MaxCP = 500,
                            MaxHP = 50,
                            MaxHeight = 0.7f,
                            MaxWeight = 1.5f,
                            MinCP = 10,
                            MinHP = 20,
                            MinHeight = 0.2f,
                            MinWeight = 0.2f,
                            NDex = (short)10,
                            Name = "Caterpie"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(7929),
                            Description = "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body",
                            HasAlolanForm = false,
                            ImgUrl = "Metapod.png",
                            Location = "Routes 24 and 25, Viridian Forest or evolve Caterpie",
                            MaxCP = 400,
                            MaxHP = 25,
                            MaxHeight = 1.5f,
                            MaxWeight = 1f,
                            MinCP = 10,
                            MinHP = 20,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)11,
                            Name = "Metapod"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8036),
                            Description = "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
                            HasAlolanForm = false,
                            ImgUrl = "Butterfree.png",
                            Location = "Evolve Metapod",
                            MaxCP = 1800,
                            MaxHP = 100,
                            MaxHeight = 1.7f,
                            MaxWeight = 1f,
                            MinCP = 10,
                            MinHP = 40,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)12,
                            Name = "Butterfree"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8147),
                            Description = "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
                            HasAlolanForm = false,
                            ImgUrl = "Weedle.png",
                            Location = "Routes 2, 24, and 25, Viridian Forest",
                            MaxCP = 500,
                            MaxHP = 50,
                            MaxHeight = 0.7f,
                            MaxWeight = 1.5f,
                            MinCP = 10,
                            MinHP = 20,
                            MinHeight = 0.2f,
                            MinWeight = 0.2f,
                            NDex = (short)13,
                            Name = "Weedle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8254),
                            Description = "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.",
                            HasAlolanForm = false,
                            ImgUrl = "Kakuna.png",
                            Location = "Routes 24 and 25, Viridian Forest",
                            MaxCP = 400,
                            MaxHP = 25,
                            MaxHeight = 1.5f,
                            MaxWeight = 1f,
                            MinCP = 10,
                            MinHP = 20,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)14,
                            Name = "Kakuna"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8367),
                            Description = "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
                            HasAlolanForm = false,
                            ImgUrl = "Beedrill.png",
                            Location = "Evolve Kakuna",
                            MaxCP = 1800,
                            MaxHP = 100,
                            MaxHeight = 1.7f,
                            MaxWeight = 1f,
                            MinCP = 10,
                            MinHP = 40,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)15,
                            Name = "Beedrill"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8475),
                            Description = "Is a small, quadruped rodent Pokémon. Its most notable feature is its large teeth.",
                            HasAlolanForm = true,
                            ImgUrl = "Rattata.png",
                            Location = "Somewhere",
                            MaxCP = 680,
                            MaxHP = 60,
                            MaxHeight = 0.5f,
                            MaxWeight = 1f,
                            MinCP = 10,
                            MinHP = 10,
                            MinHeight = 0.1f,
                            MinWeight = 0.5f,
                            NDex = (short)19,
                            Name = "Rattata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8583),
                            Description = "Is a humanoid Pokémon with an ovoid body. Hitmonlee's legs freely contract and stretch similar to a coiled spring.",
                            HasAlolanForm = false,
                            ImgUrl = "Hitmonlee.png",
                            Location = "Somewhere",
                            MaxCP = 2000,
                            MaxHP = 100,
                            MaxHeight = 1.7f,
                            MaxWeight = 1f,
                            MinCP = 30,
                            MinHP = 40,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)106,
                            Name = "Hitmonlee"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8695),
                            Description = "Has an extremely sharp sense of direction and homing instincts.",
                            HasAlolanForm = false,
                            ImgUrl = "Pidgey.png",
                            Location = "Somewhere",
                            MaxCP = 1000,
                            MaxHP = 60,
                            MaxHeight = 0.6f,
                            MaxWeight = 1.8f,
                            MinCP = 10,
                            MinHP = 10,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)16,
                            Name = "Pidgey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8802),
                            Description = "Creates gases within its body by mixing toxins with garbage, and produces more gas in higher temperatures.",
                            HasAlolanForm = false,
                            ImgUrl = "Koffing.png",
                            Location = "Somewhere",
                            MaxCP = 1650,
                            MaxHP = 100,
                            MaxHeight = 1.8f,
                            MaxWeight = 3f,
                            MinCP = 10,
                            MinHP = 40,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)109,
                            Name = "Koffing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(8913),
                            Description = "Is a tiny, brown Pokémon that seems to be perpetually buried within the earth, leaving only its head visible.",
                            HasAlolanForm = true,
                            ImgUrl = "Diglett.png",
                            Location = "Somewhere",
                            MaxCP = 1250,
                            MaxHP = 70,
                            MaxHeight = 1.2f,
                            MaxWeight = 1.8f,
                            MinCP = 10,
                            MinHP = 20,
                            MinHeight = 0.2f,
                            MinWeight = 0.5f,
                            NDex = (short)50,
                            Name = "Diglett"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000095"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(9021),
                            Description = "Resembles a giant chain of gray boulders that become smaller towards the tail.",
                            HasAlolanForm = false,
                            ImgUrl = "Onix.png",
                            Location = "Somewhere",
                            MaxCP = 2300,
                            MaxHP = 120,
                            MaxHeight = 4.7f,
                            MaxWeight = 400f,
                            MinCP = 100,
                            MinHP = 50,
                            MinHeight = 2.2f,
                            MinWeight = 200f,
                            NDex = (short)95,
                            Name = "Onix"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000092"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(9128),
                            Description = "Has no true form, due to 95% of its body being poisonous gas.",
                            HasAlolanForm = false,
                            ImgUrl = "Gastly.png",
                            Location = "Somewhere",
                            MaxCP = 1500,
                            MaxHP = 100,
                            MaxHeight = 1.5f,
                            MaxWeight = 2f,
                            MinCP = 10,
                            MinHP = 40,
                            MinHeight = 0.5f,
                            MinWeight = 0.5f,
                            NDex = (short)92,
                            Name = "Gastly"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(9241),
                            Description = "Is covered in yellow fur with two horizontal brown stripes on its back.",
                            HasAlolanForm = false,
                            ImgUrl = "Pikachu.png",
                            Location = "Somewhere",
                            MaxCP = 1500,
                            MaxHP = 80,
                            MaxHeight = 0.9f,
                            MaxWeight = 3.5f,
                            MinCP = 50,
                            MinHP = 40,
                            MinHeight = 0.4f,
                            MinWeight = 1.5f,
                            NDex = (short)25,
                            Name = "Pikachu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000150"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(9348),
                            Description = "Is a Pokémon created by science. It is a bipedal, humanoid creature with some feline features.",
                            HasAlolanForm = false,
                            ImgUrl = "Mewtwo.png",
                            Location = "Somewhere",
                            MaxCP = 3200,
                            MaxHP = 150,
                            MaxHeight = 2f,
                            MaxWeight = 35f,
                            MinCP = 1000,
                            MinHP = 90,
                            MinHeight = 1.6f,
                            MinWeight = 17.5f,
                            NDex = (short)150,
                            Name = "Mewtwo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000087"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(9460),
                            Description = "Has a snowy white, furry body, which renders it virtually invisible in snowy conditions.",
                            HasAlolanForm = false,
                            ImgUrl = "Dewgong.png",
                            Location = "Somewhere",
                            MaxCP = 1800,
                            MaxHP = 100,
                            MaxHeight = 2.8f,
                            MaxWeight = 60f,
                            MinCP = 30,
                            MinHP = 50,
                            MinHeight = 1.5f,
                            MinWeight = 30f,
                            NDex = (short)87,
                            Name = "Dewgong"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000147"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 427, DateTimeKind.Local).AddTicks(9566),
                            Description = "is filled with life energy. Dratini is constantly growing, and can thus reach lengths of over six feet.",
                            HasAlolanForm = false,
                            ImgUrl = "Dratini.png",
                            Location = "Somewhere",
                            MaxCP = 950,
                            MaxHP = 60,
                            MaxHeight = 1.5f,
                            MaxWeight = 25f,
                            MinCP = 30,
                            MinHP = 40,
                            MinHeight = 0.6f,
                            MinWeight = 7.5f,
                            NDex = (short)147,
                            Name = "Dratini"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonCatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CP");

                    b.Property<DateTime?>("Created");

                    b.Property<bool>("Gender");

                    b.Property<int>("HP");

                    b.Property<float>("Height");

                    b.Property<bool>("IsAlolan");

                    b.Property<bool>("IsShiny");

                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("UserId");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("UserId");

                    b.ToTable("PokemonCatches");
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonEvolution", b =>
                {
                    b.Property<Guid>("BasePokemonId");

                    b.Property<Guid>("EvolutionId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("BasePokemonId", "EvolutionId");

                    b.HasIndex("EvolutionId");

                    b.ToTable("PokemonEvolutions");

                    b.HasData(
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(679),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(756),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000004"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(808),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000005"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(854),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000007"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(901),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000008"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(946),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000010"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(991),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000011"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(1036),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000013"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(1087),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BasePokemonId = new Guid("00000000-0000-0000-0000-000000000014"),
                            EvolutionId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(1132),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonMove", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("MoveId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "MoveId");

                    b.HasIndex("MoveId");

                    b.ToTable("PokemonMoves");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000007"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2201),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2259),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000004"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2305),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000025"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2349),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2401),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2446),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000003"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2490),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000016"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2533),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000019"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2578),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000005"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2621),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000006"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2666),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000008"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2714),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000009"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2758),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000010"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2802),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000011"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2846),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000012"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2890),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000150"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2935),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000087"),
                            MoveId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(2985),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonMoveCatch", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("MoveId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "MoveId");

                    b.HasIndex("MoveId");

                    b.ToTable("PokemonMoveCatches");
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonType", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("TypeId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(4757),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(4811),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(4856),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(4900),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000003"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(4946),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000003"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(4990),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000004"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5035),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000005"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5084),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5128),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5172),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000007"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5215),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000008"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5259),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000009"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5303),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000010"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5346),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000011"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5396),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000012"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5440),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000012"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5485),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000013"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5528),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000013"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5572),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000014"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5616),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000014"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5659),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5708),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5752),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000019"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5795),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000106"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5839),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000016"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5882),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000016"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5926),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000109"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(5970),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000050"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6018),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000095"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6062),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000095"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6106),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000092"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6149),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000092"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6194),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000025"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6238),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000150"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6286),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000087"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6331),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000087"),
                            TypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6375),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PokemonId = new Guid("00000000-0000-0000-0000-000000000147"),
                            TypeId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(6418),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonUser", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("UserId");

                    b.Property<short>("Catches");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("PokemonId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PokemonUsers");
                });

            modelBuilder.Entity("Pokebook.core.Models.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Colour = "#A8A878",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(9667),
                            Name = "Normal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Colour = "#C03028",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(9728),
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Colour = "#A890F0",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(9779),
                            Name = "Flying"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Colour = "#A040A0",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(9828),
                            Name = "Poison"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Colour = "#E0C068",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(9877),
                            Name = "Ground"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Colour = "#B8A038",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(9924),
                            Name = "Rock"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Colour = "#A8B820",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 429, DateTimeKind.Local).AddTicks(9973),
                            Name = "Bug"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Colour = "#705898",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(25),
                            Name = "Ghost"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Colour = "#B8B8D0",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(74),
                            Name = "Steel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Colour = "#F08030",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(121),
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Colour = "#6890F0",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(168),
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Colour = "#78C850",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(215),
                            Name = "Grass"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Colour = "#F8D030",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(262),
                            Name = "Electric"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Colour = "#F85888",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(309),
                            Name = "Psychic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Colour = "#98D8D8",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(362),
                            Name = "Ice"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Colour = "#7038F8",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(409),
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Colour = "#705848",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(457),
                            Name = "Dark"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Colour = "#EE99AC",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(504),
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.TypeAdvantage", b =>
                {
                    b.Property<Guid>("AdvantageTypeId");

                    b.Property<Guid>("DisadvantageTypeId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("AdvantageTypeId", "DisadvantageTypeId");

                    b.HasIndex("DisadvantageTypeId");

                    b.ToTable("TypeAdvantages");

                    b.HasData(
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2048),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2107),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2159),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000d"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2206),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2253),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000f"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2299),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-000000000006"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2345),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000e"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2391),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2437),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            AdvantageTypeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            DisadvantageTypeId = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(2487),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("CoverPicture");

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FavoritePokemon");

                    b.Property<string>("FavoritePokemonGame");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTime>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<int>("NumberOfFriends");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            CoverPicture = "Mt._Molteau.png",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(4638),
                            EmailConfirmed = false,
                            FavoritePokemon = "Pikachu",
                            FavoritePokemonGame = "Pokemon Red",
                            FirstName = "Tyrion",
                            LastName = "Lannister",
                            LockoutEnabled = false,
                            LockoutEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfFriends = 0,
                            PasswordHash = "PW7h5Yl70M3o3LA9YQ5wUG+ycD7H01aXrDizkpC4lBX7hP/k",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "Pikachu.png",
                            TwoFactorEnabled = false,
                            UserName = "TyrionLannister"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AccessFailedCount = 0,
                            CoverPicture = "mountain.jpg",
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(4790),
                            EmailConfirmed = false,
                            FirstName = "Jon",
                            LastName = "Snow",
                            LockoutEnabled = false,
                            LockoutEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfFriends = 0,
                            PasswordHash = "PW7h5Yl70M3o3LA9YQ5wUG+ycD7H01aXrDizkpC4lBX7hP/k",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "Magikarp.png",
                            TwoFactorEnabled = false,
                            UserName = "JonSnow"
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.UserChat", b =>
                {
                    b.Property<Guid>("ChatId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime?>("Created");

                    b.Property<Guid>("Id");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChats");

                    b.HasData(
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(5736),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(5795),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ChatId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2019, 11, 2, 14, 13, 45, 430, DateTimeKind.Local).AddTicks(5843),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Pokebook.core.Models.Friendship", b =>
                {
                    b.HasOne("Pokebook.core.Models.User")
                        .WithMany("Friendships")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Pokebook.core.Models.Message", b =>
                {
                    b.HasOne("Pokebook.core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.Move", b =>
                {
                    b.HasOne("Pokebook.core.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonCatch", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany("PokemonCatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonEvolution", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Evolution")
                        .WithMany("PokemonEvolutions")
                        .HasForeignKey("BasePokemonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pokebook.core.Models.Pokemon", "BasePokemon")
                        .WithMany("PokemonPreEvolutions")
                        .HasForeignKey("EvolutionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonMove", b =>
                {
                    b.HasOne("Pokebook.core.Models.Move", "Move")
                        .WithMany("PokemonMoves")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonMoves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonMoveCatch", b =>
                {
                    b.HasOne("Pokebook.core.Models.Move", "Move")
                        .WithMany("PokemonMoveCatches")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.PokemonCatch", "Pokemon")
                        .WithMany("PokemonMoveCatches")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonType", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.Type", "Type")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.PokemonUser", b =>
                {
                    b.HasOne("Pokebook.core.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokebook.core.Models.TypeAdvantage", b =>
                {
                    b.HasOne("Pokebook.core.Models.Type", "AdvantageType")
                        .WithMany("AdvantagesOver")
                        .HasForeignKey("AdvantageTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pokebook.core.Models.Type", "DisadvantageType")
                        .WithMany("DisadvantagesOver")
                        .HasForeignKey("DisadvantageTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pokebook.core.Models.UserChat", b =>
                {
                    b.HasOne("Pokebook.core.Models.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokebook.core.Models.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
